- name: configure the master redis server
  hosts: redis-master
  become: True
  tags: master
  vars:
    redis_version: 3.2.9
    redis_as_service: true
  roles:
    - role: davidwittman.redis

- name: configure redis slaves
  become: True
  tags: slave
  hosts: redis-slave
  vars:
    redis_version: 3.2.9
    redis_as_service: true
    redis_slaveof: 192.168.9.40 6379
  roles:
    - role: davidwittman.redis

- name: configure redis sentinel nodes
  hosts: redis-sentinel
  tags: sentinel
  vars:
    - redis_version: 3.2.9
    - redis_sentinel_monitors:
      - name: master01
        host: 192.168.9.40
        port: 6379
  roles:
    - davidwittman.redis
